version: '3'

services:
  
  explorer:
    image: hyperledger/explorer
    #image: wanliqun/fabric-explorer
    #environment:
    #  - DATABASE_HOST=db0.deepchain.network
    #  - DATABASE_PORT=5432
    #  - DATABASE_DATABASE=fabricexplorer
    #  - DATABASE_USERNAME=hppoc
    #  - DATABASE_PASSWORD=password
    #volumes:
    #  - ./configs/notarynet/crypto:/tmp/crypto
    #  - ./fabric-bin:/fabric-bin
    #  - ./configs/notarynet/config.json:/opt/explorer/app/platform/fabric/config.json    
    networks:
      - fabric 
      - swarm
    ports:
      - "8080:8080"
    command: node /opt/explorer/main.js
    
networks:
  default:
    external:
      name: fabric-overlay
  swarm:
    external:
      name: swarm-overlay